resolved mock problem

diff --git a/build-agent-client b/build-agent-client
--- a/build-agent-client
+++ b/build-agent-client
@@ -1,15 +1,23 @@
 #!/bin/sh
 # a very simple script to grab instructions from build server and run them
+
 # cron doesn't put me in my home
 cd /home/buildagent
+LOG="/home/buildagent/upload-$$.log"
+
+# cron doesn't set up my PATH correctly (can cause mock failure)
+PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/buildagent/bin
 
 # don't run if there is something already running
 [ -f build-script ] && exit 0
-touch build-script
 
 # don't run if the loadavg hits 1 or more
-#LOADAVG="`cat /proc/loadavg`"
-#[ "${LOADAVG%%.*}" -lt 1 ] || exit
+LOADAVG="`cat /proc/loadavg`"
+[ "${LOADAVG%%.*}" -lt 1 ] || exit
+
+# don't run if there are already 5 uploads or more in progress
+UPLOADS="`ls -1 result-*.tgz | wc -l`"
+[ $UPLOADS -lt 1 ] || exit
 
 # get the MAC address
 HWADDR="`ifconfig |fgrep HWaddr |head -1 |tr -d ':'`"
@@ -47,13 +55,16 @@ cd build-dir
 STATUS="fail"
 if sh ../build-script > build-script-output 2>&1
 then
+    echo "sh returned $? - OK" >>$LOG
 	STATUS="ok"
+else
+    echo "sh returned $? - fail" >>$LOG
 fi
+cat build-script-output >>$LOG
 
 RESULT="result-$$.tgz"
-LOG="upload-$$.log"
 
-echo "Creating archive jobid=$JOB_ID agentid=$MAC status=$STATUS" >$LOG
+echo "Creating archive jobid=$JOB_ID agentid=$MAC status=$STATUS" >>$LOG
 tar cvfz ../$RESULT . >>$LOG 2>&1
 
 cd ..
diff --git a/build_project/patchadams b/build_project/patchadams
--- a/build_project/patchadams
+++ b/build_project/patchadams
@@ -4,7 +4,8 @@
 # $1 argument is the project url to get files from
 # $2 argument is a URL to the source RPM to patch
 
-set -ex
+set -e
+set -x
 
 PROJECT_URL="$1"
 SRCRPM_URL="$2"
@@ -27,10 +28,15 @@ diff $MOCK64.cfg /etc/mock/$MOCK64.cfg || cp $MOCK64.cfg /etc/mock
 diff $MOCK32.cfg /etc/mock/$MOCK32.cfg || cp $MOCK32.cfg /etc/mock
 
 # initialize the chroot
-mock -r $MOCK64 --init
+# note: mock may not exit non-zero on failure
+# so check output for ERROR
+mock -r $MOCK64 --init |tee mock-output
+grep ^ERROR mock-output && exit 1
 
 # install source rpm
-mock -r $MOCK64 --shell "rpm -ihv  $SRCRPM_URL" 
+mock -r $MOCK64 --shell "rpm -ihv  $SRCRPM_URL"  |tee mock-output
+grep ^ERROR mock-output && exit 1
+
 
 # there should be exactly 1 spec file in the spec directory
 PKGNAME="`basename $MOCK64_BUILD/SPECS/*.spec .spec`"
@@ -61,7 +67,9 @@ then
 fi
 
 # recreate source rpm
-mock -r $MOCK64 --shell "rpmbuild -bs /builddir/build/SPECS/$PKGNAME.spec" 
+mock -r $MOCK64 --shell "rpmbuild -bs /builddir/build/SPECS/$PKGNAME.spec"  |tee mock-output
+grep ^ERROR mock-output && exit 1
+
 
 NEW_SRCRPM="`basename $MOCK64_BUILD/SRPMS/*.src.rpm`"
 if [ -z "$NEW_SRCRPM" ]
@@ -75,21 +83,15 @@ mkdir SRPMS
 cp -v $MOCK64_BUILD/SRPMS/$NEW_SRCRPM SRPMS
 
 # now rebuild for 64bit
-if ! mock -r $MOCK64 --rebuild SRPMS/$NEW_SRCRPM
-then
-    echo "ERROR: mock rebuild 64 failed"
-    exit 1
-fi
+mock -r $MOCK64 --rebuild SRPMS/$NEW_SRCRPM |tee mock-output
+grep ^ERROR mock-output && exit 1
 
 mkdir x86_64
 cp -v $MOCK64_BUILD/RPMS/* x86_64
 
 # and finally for 32bit
-if ! mock -r $MOCK32 --rebuild SRPMS/$NEW_SRCRPM
-then
-    echo "ERROR: mock rebuild 32 failed"
-    exit 1
-fi
+mock -r $MOCK32 --rebuild SRPMS/$NEW_SRCRPM |tee mock-output
+grep ^ERROR mock-output && exit 1
 
 mkdir i386
 cp -v $MOCK32_BUILD/RPMS/* i386
